export const MAPBOX_API_KEY = process.env.NEXT_PUBLIC_MAPBOX_API_KEY

export const IPFS_CLIENT_PROJECT = process.env.NEXT_PUBLIC_IPFS_CLIENT_PROJECT
export const IPFS_CLIENT_SECRET = process.env.NEXT_PUBLIC_IPFS_CLIENT_SECRET
